[package]
name = "study"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
octocrab = "0.16"
tokio = { version = "1", features = ["full"] }
serde_json = "1.0"
blake3 = "1"
walkdir = "2"